### ISSUE TITLE
samase 0.82 and latest aise

### ISSUE THREAD

**Issue by eudmaptester** [neivv/samase_plugin#1]
Hello. Can you share with latest version cause 0.82 cant compile .exe which include latest aise.dll ( can only with  aise.dll 2.35 or older) The error is "Newer samase is required . plugin API version is 34. requires version 37).   May be you can update link on staredit - http://www.staredit.net/?downloadAttachment=11895&key=9807360 

P.S>Many thanks , samase is really awesome

**Comment by neivv** [comment]
Ah yea the SEN version has gotten bit out of date wrt. things aise requires 🙁

Here's the newest version
[samase.zip](https://github.com/neivv/samase_plugin/files/10420148/samase.zip)

I'll update the link at SEN to have this build bit later too

**Comment by eudmaptester** [comment]
Thanks a lot. it works now . Im happy!
