### ISSUE TITLE
Samase loader out of date

### ISSUE THREAD

**Issue by eudmaptester** [neivv/samase_plugin#2]
Hello. Can you please update to new version (plugin API error :requires version 38). Link you have provided last january https://github.com/neivv/samase_plugin/files/10420148/samase.zip

**Comment by neivv** [comment]
[samase.zip](https://github.com/neivv/samase_plugin/files/11634595/samase.zip)

Here, sorry for the trouble.

**Comment by eudmaptester** [comment]
> [samase.zip](https://github.com/neivv/samase_plugin/files/11634595/samase.zip)
> 
> Here, sorry for the trouble.

Now works) Thanks a lot
